name: Publish Python Package

on:
  push:
    tags:
      - '*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out source repository
        uses: actions/checkout@v4

      - uses: nixbuild/nix-quick-install-action@v30
        with:
          nix_on_tmpfs: true

      - name: Hash flake
        shell: bash
        run: |
          # Manually compute hash because hashFiles doesn't work outside the workspace
          # (https://github.com/actions/toolkit/issues/1035.)
          shopt -s extglob
          flake_hash=$(sha256sum flake.@(nix|lock) | sha256sum | sed 's/[[:blank:]].*//')
          echo "flake_hash=${flake_hash}" >> $GITHUB_ENV

      - name: Cache Nix Store
        uses: nix-community/cache-nix-action@v6
        with:
          primary-key: nix-${{ runner.os }}-${{ env.flake_hash }}
          restore-prefixes-first-match: nix-${{ runner.os }}-
          # Purge old caches and garbage collect new one if there wasn't an exact match
          purge: true
          purge-prefixes: nix-${{ runner.os }}-
          purge-created: 0
          purge-primary-key: never
          gc-max-store-size-linux: 0

      - name: Set up Nix environment
        uses: nicknovitski/nix-develop@v1

      - name: Build with Nix
        run: nix build

      - name: Find built wheel
        id: find-wheel
        run: |
          WHEEL_PATH=$(find result/ -name "*.whl" | head -n1)
          if [ -z "$WHEEL_PATH" ]; then
            echo "No wheel file found in result/"
            exit 1
          fi
          echo "wheel=$WHEEL_PATH" >> $GITHUB_OUTPUT

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          nix develop --command twine upload "${{ steps.find-wheel.outputs.wheel }}"

      - name: Cleanup
        run: rm -rf result
